title: Wilde Chu
# email: your-email@example.com
description: CS Math Undergrad @ RPI
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wildechu23.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wildechu23

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - projects